### ISSUE TITLE
Output directory

### ISSUE THREAD

**Issue by 4eh5xitv6787h645ebv** [graham-walker/youtube-dl-react-viewer#16]
Output directory is being put in so not sure why its saying it's not there. Is probably just me getting it wrong. 
.env file:

    'OUTPUT_DIRECTORY': {
        type: String,
        required: true,
        default: '/home/jake/Documents',
    },

Is giving this error. :
0|youtube-dl-react-viewer  | Error: Required environment variable "OUTPUT_DIRECTORY" not specified.
0|youtube-dl-react-viewer  |     at parse (file:///home/jake/Documents/Youtube%20Channels/a/youtube-dl-react-viewer/youtube-dl-express-backend/parse-env.js:87:27)
0|youtube-dl-react-viewer  |     at file:///home/jake/Documents/Youtube%20Channels/a/youtube-dl-react-viewer/youtube-dl-express-backend/parse-env.js:143:16
0|youtube-dl-react-viewer  |     at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
0|youtube-dl-react-viewer  |     at async Loader.import (internal/modules/esm/loader.js:166:24)

**Comment by JamoDevNich** [comment]
Change that part of the .env to this:
```
OUTPUT_DIRECTORY=/home/jake/Documents
```

An example env file is in the backend folder, called `.env.sample`. You might need to enable hidden files to see it if you're using Mac/Linux
