### ISSUE TITLE
ERROR: Version in "./docker-compose.yaml" is unsupported.

### ISSUE THREAD

**Issue by Snake883** [graham-walker/youtube-dl-react-viewer#19]
Received the error message:
> ERROR: Version in "./docker-compose.yaml" is unsupported.

Followed these instructions:
`sudo apt install docker-compose`
[Running in Docker](https://github.com/graham-walker/youtube-dl-react-viewer#running-in-docker)

**Comment by JamoDevNich** [comment]
Which docker-compose version are you running?  

If it's older than 1.27.4, could you try `apt remove docker-compose` and install from pypi instead `pip3 install docker-compose`?

**Comment by snakyjake1** [comment]
> Which docker-compose version are you running?

`docker-compose version 1.17.1, build unknown`

Installing the pip version worked.  

Thank you.

**Comment by Snake883** [comment]
> Which docker-compose version are you running?

`docker-compose version 1.17.1, build unknown`

Installing the pip version worked.  

Thank you.
