### ISSUE TITLE
How to install and update youtube-dl in docker container? 

### ISSUE THREAD

**Issue by Snake883** [graham-walker/youtube-dl-react-viewer#20]
[Instructions](https://github.com/graham-walker/youtube-dl-react-viewer#running-in-docker).
### Outside of Docker
`$ docker exec -it youtube-dl-react-viewer_app_1 /bin/sh`

### Inside Docker
`/opt/youtube-dl-react-viewer/youtube-dl-express-backend # apt-get install youtube-dl`
`/bin/sh: apt-get: not found`

### Solution
`$ pip install youtube-dl`

That works, but youtube-dl will no longer be updated via webapp:
> It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.

![image](https://user-images.githubusercontent.com/8312560/112555096-beba1e00-8d84-11eb-9115-e2fc0d63e305.png)

**Comment by JamoDevNich** [comment]
By default, the update button in the webapp calls `youtube-dl -U`. To change it to run `pip install --upgrade youtube-dl` instead, you can try this command in the docker container:  
```
sed -i 's/parsedEnv.YOUTUBE_DL_PATH, \['\''-U'\''\]/'\''pip'\'', \['\''install'\'', '\''--upgrade'\'', '\''youtube-dl'\''\]/g' /opt/youtube-dl-react-viewer/youtube-dl-express-backend/routes/admin.route.js
```

**Comment by graham-walker** [comment]
As of version 1.3.0 updating youtube-dl if it was installed from a package manager is supported by setting the environment variable `YOUTUBE_DL_UPDATE_COMMAND`.
