### ISSUE TITLE
Future request: Save channels avatars

### ISSUE THREAD

**Issue by kodxana** [graham-walker/youtube-dl-react-viewer#3]
Is it possible to save channels avatars instead of basic dummy avatar image?

**Comment by graham-walker** [comment]
It is possible to do this in the current version, but avatar images must be saved manually:

1. Open the avatars folder in the configured output directory
2. Open the extractor folder for the website of your channel (for example if your channel is a YouTube channel open the youtube folder)
3. Save the avatar image to this folder
4. Rename the avatar image so it is exactly the same as the channel name and has the file extension `.jpg`
    - If the channel name contains characters that cannot be included in a file name, replace them with underscores ("_")

**Comment by kodxana** [comment]
The thing is I save avatar and it's not updating on app side.

**Comment by kodxana** [comment]
![obraz](https://user-images.githubusercontent.com/16674412/100451095-18505b80-30b7-11eb-9189-0308af409ea0.png)
![obraz](https://user-images.githubusercontent.com/16674412/100451152-328a3980-30b7-11eb-92f8-15f4d2c51521.png)

Tried to restart container

**Comment by kodxana** [comment]
@graham-walker any ideas what might be issue? BTW your tool is amazing :)
