### ISSUE TITLE
Unable to find error message

### ISSUE THREAD

**Issue by dyslexicjedi** [graham-walker/youtube-dl-react-viewer#4]
Using Docker. I added a job called SpaceX, with a link of https://www.youtube.com/c/SpaceX/videos

I run the job and I only get "Failed to start job". I checked for a error.txt file, and none can be found in any directory. 

Docker Command: 
`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='youtube-dl-react-viewer' --net='proxynet' -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" -e 'SUPERUSER_PASSWORD'='<password>' -e 'JWT_TOKEN_SECRET'='<token>' -e 'YOUTUBE_DL_PATH'='/opt/youtube-dl-react-viewer/youtube-dl' -e 'OUTPUT_DIRECTORY'='/data' -p '5002:5000/tcp' -v '/mnt/user/Archive/ReactViewer/':'/data':'rw' 'registry.dyslexicjedi.com/dyslexicjedi/youtube-dl-react-viewer' `

I check the docker log and no errors were reported there either. Any thoughts?

**Comment by JamoDevNich** [comment]
Could be a write permissions issue (on the output directory), or an issue with the youtube-dl executable.

Could you check if there is a youtube-dl executable inside the container in the folder you specified (/opt/youtube-dl-react-viewer), and whether it has execute permissions?

There may be a more descriptive error available in the container logs `docker container logs <containername>`.

**Comment by dyslexicjedi** [comment]
Nope. The environment variable is set correctly based on docker log output.

`Using user-defined value for YOUTUBE_DL_PATH=/opt/youtube-dl-react-viewer/youtube-dl`

From the docker's console, I'm able to see the file, and it's set to executable. (This was done in a Jenkins step)
`/opt/youtube-dl-react-viewer # ls -lh
total 2M     
-rw-r--r--    1 root     root        1.8K Nov 27 15:58 Dockerfile
-rw-r--r--    1 root     root         685 Nov 27 15:58 FUNDING.yml
-rw-r--r--    1 root     root        1.0K Nov 27 15:58 LICENSE
-rw-r--r--    1 root     root       22.3K Nov 27 15:58 README.md
-rw-r--r--    1 root     root         769 Nov 27 15:58 docker-compose.yaml
-rw-r--r--    1 root     root          91 Nov 27 15:58 install.bat
-rw-r--r--    1 root     root          98 Nov 27 15:58 install.sh
-rw-r--r--    1 root     root          64 Nov 27 15:58 start-server.bat
-rw-r--r--    1 root     root          41 Nov 27 15:58 start-server.sh
-rwxrwxrwx    1 root     root        1.7M Nov 27 18:53 youtube-dl
drwxr-xr-x    1 root     root         288 Nov 27 19:06 youtube-dl-express-backend
drwxr-xr-x    1 root     root         140 Nov 27 19:02 youtube-dl-react-frontend`

**Comment by dyslexicjedi** [comment]
I figured it out, when you execute youtube-dl in the docker environment it's looking for python. But python isn't mapped, it's python3. So I had to add `ln -s /usr/bin/python3 /usr/bin/python`

Once I did that, it started no problem. You may want to add that symlink to the dockerfile.

**Comment by JamoDevNich** [comment]
That's interesting, I haven't run into that issue (I use the wheel from pip).

Python 2.x is typically installed at `/usr/bin/python` by default, so it might be a better idea to install python2 instead of a python3 symlink. It's already installed as part of the build process, but removed towards the end of the build.

https://github.com/graham-walker/youtube-dl-react-viewer/blob/main/Dockerfile#L19-L20
