### ISSUE TITLE
Playing video stops youtube-dl downloads

### ISSUE THREAD

**Issue by kodxana** [graham-walker/youtube-dl-react-viewer#8]
When you play video in web GUI it stops running youtube-dl jobs. So you need to start job again.

**Comment by graham-walker** [comment]
This should not be the case. Can you provide logs from the console? My guess is that the server is crashing and restarting when you are playing a video which would cause the job to stop.

**Comment by kodxana** [comment]
Apparently this issue exist in old version. Build docker image with Version: 1.1.1 and issue not happening.
